name: Print Message

description: 'Prints a custom message'

inputs:
  message:
    description: 'The message to print'
    required: true
    default: 'Hello, World!'

runs:
  using: 'shell'
  steps:
    - name: Print the Message
      run: echo "${{ inputs.message }}"
